function makeCodes() {
	let codes = {
		'01': 'a reported medical emergency',//'a reported medical emergency'//'a reported patient with abdominal pain',
		'02': 'a reported medical emergency',//'a reported allergic reaction',
		'03': 'a reported injury',//'a reported animal bite',
		'04': 'a reported injury',//'a reported assault',
		'05': 'a reported medical emergency',//'a reported patient with back pain',
		'06': 'a reported medical emergency',//'a reported patient with difficulty breathing',
		'07': 'a reported injury due to burns or explosions',
		'08': 'a reported Hazardous Materials or CO incident',
		'09': 'a reported patient in cardiac arrest',
		'10': 'a reported medical emergency',//'a reported chest pain patient',
		'11': 'a reported choking patient',
		'12': 'a reported medical emergency',//'a reported seizure patient',
		'13': 'a reported medical emergency',//'a reported diabetic emergency',
		'14': 'a reported water-related emergency',
		'15': 'a reported injury',//'a reported electrical injury',
		'16': 'a reported injury',//'a reported eye injury',
		'17': 'a reported injury',//'a reported fall victim',
		'18': 'a reported medical emergency',//'a reported headache',
		'19': 'a reported medical emergency',//'a reported cardiac problem',
		'20': 'a reported environmental emergency',
		'21': 'a reported patient who may be bleeding',
		'22': 'a reported non-vehicle rescue',
		'23': 'a reported overdose',
		'24': 'a reported medical emergency',//'a reported obstetrical emergency',
		'25': 'a reported medical emergency',//'a reported behavioral emergency',
		'26': 'a reported medical emergency',//'a reported sick person',
		'27': 'a reported weapons-related injury',
		'28': 'a reported medical emergency',//'a reported stroke',
		'29': 'a reported vehicle crash',
		'30': 'a reported injury',
		'31': 'a reported medical emergency',//'a reported unconscious person',
		'32': 'an unknown problem',
		'33': 'a reported need for transportation',
		'FAFA': 'a reported automatic fire alarm',
		'FAFARD': 'a reported automatic fire alarm',
		'FAIRCR': 'a reported aircraft fire',
		'FBARN1': 'a reported barn fire - 1st alarm',
		'FBARN2': 'a reported barn fire - 2nd alarm',
		'FBARN3': 'a reported barn fire - 3rd alarm',
		'FBARN4': 'a reported barn fire - 4th alarm',
		'FCB': 'a reported controlled burn',
		'FCODET': 'a reported CO detector activation',
		'FHMINI': 'a reported Hazardous Materials incident',
		'FHMNS': 'a reported Hazardous Materials incident',
		'FHMOUI': 'a reported Hazardous Materials incident',
		'FHMSTR': 'a reported Hazardous Materials incident',
		'FLZ': 'to assist at a helicopter landing zone',
		'FMA': 'to assist with a fire department medical assist',
		'FMASTN': 'a reported mass transportation emergency',
		'FMISC': 'to assist on a fire call',
		'FOTRES': 'to assist on a fire call',
		'FOUI': 'to assist on a fire call',
		'F1ST': 'to assist on a fire call',
		'F2ND': 'to assist on a fire call - 2nd alarm',
		'F3RD': 'to assist on a fire call - 3rd alarm',
		'F4TH': 'to assist on a fire call - 4th alarm',
		'FSTR1':'to assist on a fire call',
		'FSTR2': 'to assist on a fire call - 2nd alarm',
		'FSTR3': 'to assist on a fire call - 3rd alarm',
		'FSTR4': 'to assist on a fire call - 4th alarm',
		'FVEHICLE': 'a reported vehicle fire',
		'FVEHLG': 'a reported vehicle fire',
		'FVEHSM': 'a reported vehicle fire',
		'FVSNI': 'a reported vehicle vs a structure incident',
		'FWARES': 'a reported water rescue incident',
		'FWF': 'to assist on a wildfire call',
		'FWFSTR': 'to assist on a wildfire call endangering a structure',
		'FWFVEH': 'to assist on a wildfire call endangering a vehicle',
		'FXFER1': 'on a transfer',
		'FXFER2': 'on a transfer',
		'FXFER3': 'on a transfer',
		'FXFER4': 'on a transfer',
		'MUTAID': 'to provide mutual aid',
		'XFER': 'on a transfer',
		'PAANI': 'an incident involving a reported vehicle crash',
		'EREF': 'assist another emergency unit with a patient',
		'EROUT': 'provide standby services'
	};
	return codes;
}

function municipalCodeMaker(){
	let codes = {
		'CB':	'Carlisle Barracks',
		'HW':	'Hopewell Township',
		'NB':	'Borough of Newburg',
		'ST':	'Shippensburg Township',
		'SB':	'Borough of Shippensburg',
		'SF':	'Borough of Shippensburg',
		'SH':	'Southampton Township',
		'UM':	'Upper Mifflin Township',
		'NN':	'North Newton Township',
		'NW':	'Borough of Newville',
		'SN':	'South Newton Township',
		'UF':	'Upper Frankford Township',
		'WP':	'West Pennsboro Township',
		'PN':	'Penn Township',
		'CK':	'Cooke Township',
		'DK':	'Dickinson Township',
		'LF':	'Lower Frankford Township',
		'NM':	'North Middleton Township',
		'CA':	'Borough of Carlisle',
		'SM':	'South Middleton Township',
		'MH':	'Borough of Mt. Holly',
		'MX':	'Middlesex Township',
		'MN':	'Monroe Township',
		'SS':	'Silver Spring Township',
		'MB':	'Borough of Mechanicsburg',
		'HM':	'Hampden Township',
		'NV':	'Naval Support Activity',
		'UA':	'Upper Allen Township',
		'SR':	'Borough of Shiremanstown',
		'LA':	'Lower Allen Township',
		'EP':	'East Pennsboro Township',
		'WB':	'Borough of Wormleysburg',
		'CH':	'Borough of Camp Hill',
		'LB':	'Borough of Lemoyne',
		'NC':	'New Cumberland Boro',
		'HC':	'Huntingdon County',
		'MF':	'Mifflin County',
		'JC':	'Juniata County',
		'PC':	'Perry County',
		'AC':	'Adams County',
		'YC':	'York County',
		'LN':	'Lancaster County',
		'DC':	'Dauphin County',
		'LE':	'Lebanon County'
	}
	return codes;

}
module.exports.municipalCodeMaker = municipalCodeMaker;
module.exports.makeCodes = makeCodes;
